config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  get 'pages/hiw'
  resources :posts
  resources :categories
  resources :listings
  get 'signup', to: 'sellers#new'
  resources :sellers, except:[:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/categories_post.rb
class CategoryPost < ActiveRecord::Base
	belongs_to :category
	belongs_to :post
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true, length: { miminum: 3, maximum: 25}
	has_many :post_categories
	has_and_belongs_to_many :posts, through: :categories_posts
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates :name, :description, :price, :condition, :location, presence: true
	validates :name, length: { minimum: 10, maximum: 100 }
	validates :description, length: { minimum: 25, maximum: 1000 }
	has_attached_file :image, styles: { medium: ["300x300>", :jpg, :quality => 70], thumb: 
  	                ["100x100>", :jpg, :quality => 70],  large:  
  	                ['1000>', :jpg, :quality => 70] }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
    has_and_belongs_to_many :posts
    belongs_to :seller
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :description, presence: true
  has_attached_file :image, styles: { medium: ["300x300>", :jpg, :quality => 70], thumb: 
  	                ["100x100>", :jpg, :quality => 70], large:  
  	                ['600>', :jpg, :quality => 70] }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  has_many :post_categories
  has_and_belongs_to_many :categories, through: :categories_posts
  has_and_belongs_to_many :listings
end

app/models/seller.rb
class Seller < ActiveRecord::Base
	validates :sellername, presence: true,
	uniqueness: { case_sensitive: false },
	length: { minimum: 3, maximum: 25 }
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
	length: { maximum: 105 },
	uniqueness: { case_sensitive: false },
	format: { with: VALID_EMAIL_REGEX }
	
	validates :location, presence: true,
	length: { minimum: 3, maximum: 25 }
	
	VALID_SITE_REGEX = /\A[w]+[w]+[w]+.[a-z\d\-.]+\.[a-z]+\z/i
	validates :site, presence: true,
	uniqueness: { case_sensitive: false },
	length: { minimum: 3, maximum: 100 },
	format: { with: VALID_SITE_REGEX }
	
	before_save { self.email = email.downcase }
	
	has_many :listings, dependent: :destroy #all listings associated will be destroyed on account termination
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_seller, :logged_in?

  def current_seller
  	@current_seller ||= Seller.find(session[:seller_id]) if session[:seller_id]
  end

  def logged_in?
  	#!current_seller.nil?
    !!current_seller
  end

  def require_seller
  	if !logged_in?
      flash[:notice] = "You need to be an active seller to make changes to a seller's account"
      redirect_to root_path
  	end
  end
  
  def require_same_seller
        if current_seller != @listing.seller && !current_seller.admin?
            redirect_to root_path
        end
  end

  def require_admin
      if (logged_in? && !current_seller.admin) || (!logged_in?)
        redirect_to root_path
      end
    end
  end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

before_action :set_category, only: [:edit, :update, :show, :destroy]
before_action :require_admin, except: [:index, :show]

	def index
		@category = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(c_params)
		if @category.save
			redirect_to category_path(@category)
		else
			render 'new'
		end	
	end

	def edit
	end

	def update
		if @category.update(c_params)
			redirect_to category_path(@category)
		else
			render 'edit'
		end
	end

	def show
		@list = Category.all
		@category_posts = @category.posts
	end

	def destroy
		@category.destroy
		redirect_to categories_path
	end

private
	def c_params
		params.require(:category).permit(:name)
	end

	def set_category
		@category = Category.find(params[:id])
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    
    #execute in same order
    before_action :set_listing, only: [:show, :edit, :update, :destroy]
    before_action :require_seller, only: [:show, :edit, :update, :destroy]
    before_action :require_same_seller, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:index]
	def index
		@listing = Listing.all
	end

	def new
		@listing = Listing.new
    end

    def create
    	@listing = Listing.new(listing_params)
        @listing.seller = current_seller
    	if @listing.save
    		redirect_to listing_path(@listing)
    	else
    		render 'new'
    	end
    end

    def edit
    end

    def update
        if @listing.update(listing_params)
    		redirect_to listing_path(@listing)
    	else 
    		render 'edit'
    	end
    end

    def show
         @listing_seller = @listing.seller
         @listing_posts = @listing.posts
    end

    def destroy
        @listing.destroy
        redirect_to listings_path
    end

    private
    def listing_params
       params.require(:listing).permit(:name, :description, :image, :location, :price, :condition)
    end

    def set_listing
        @listing = Listing.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def landing
	end

	def hiw
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  #before_action :require_seller, except: [:show]
  before_action :require_admin, except: [:show]

  def index
    @post = Post.all
  end

  def new
	  @post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  	  flash[:success] = "Post was successfully created"
  	   redirect_to post_path(@post)
  	else
  	  render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_listings = @post.listings
  end 

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to post_path(@post)
      else
        render 'edit'
      end
  end  
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
  private
  def post_params
  	params.require(:post).permit(:title, :description, :image, category_ids:[])
  end 
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

	before_action :set_seller, only: [:edit, :update, :show, :destroy]
	before_action :require_seller, except:[:new, :create, :show]
	before_action :require_same_seller, only: [:edit, :update, :index]
	before_action :require_admin, only: [:index]

	def index
		@seller = Seller.all
	end

	def new
		@seller = Seller.new
	end

	def create
		@seller = Seller.new(seller_params)
			if @seller.save
				#session[:seller_id] = @seller.id
				redirect_to seller_path(@seller)
			else
				render 'new'
			end
	end

	def edit
	end

	def update
			if @seller.update(seller_params)
				redirect_to seller_path(@seller)
			else
				render 'edit'
			end
	end

	def show
		@seller_listings = @seller.listings
	end	

	def destroy
		@seller.destroy
		redirect_to categories_path
	end

	private
		def seller_params
			params.require(:seller).permit(:sellername, :email, :location, :site, :password, :password_confirmation)
		end
		
		def set_seller
			@seller = Seller.find(params[:id])
		end



		def require_same_seller
      		if logged_in? && current_seller != @seller
        	redirect_to root_path
      	end
    	end
		
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
	seller = Seller.find_by(email: params[:session][:email].downcase)
	if seller && seller.authenticate(params[:session][:password])
		#session[:seller_id] places a temporary cookie on the browser window which ends when the browser is closed
		session[:seller_id] = seller.id
		flash[:success] = 'You have successfully logged in'
		redirect_to categories_path
	else
		render 'new'
	end
end

def destroy
	session[:seller_id] = nil
	flash[:success] = 'You have successfully logged out'
	redirect_to categories_path
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<h1 style="text-align:center">Edit Category</h1>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

			<%= form_for @category do |f| %>

			<%= f.label :name %><br />
			<%= f.text_field :name, class: "form-control" %>

			<%= f.submit %>
			
			<% end %>
		</div>
	</div>

app/views/categories/index.html.erb
<div class = "container-fluid">
	<div class="btn-group btn-group-justified" role="group">
    	<% @category.each do |category| %>
			<div class="btn-group" role="group">
    			<button type="button">
					<%= link_to "#{category.name}", category_path(category), class: "btn btn-default" %>
				</button>
			</div>
         <% end %>
	</div>
</div>
   

app/views/categories/new.html.erb
<h1 style="text-align:center">Add new Category</h1>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for @category do |f| %>
			
				<%= f.label :name %><br />
				<%= f.text_field :name, class: "form-control" %>

				<%= f.submit %>
			<% end %>
		</div>
	</div>

app/views/categories/show.html.erb
<div class = "container-fluid">
	<div class="btn-group btn-group-justified" role="group">
    	<% @list.each do |category| %>
			<div class="btn-group" role="group">
    			<button type="button">
    				<%= link_to "#{category.name}", category_path(category), class: "btn btn-default" %>
				</button>
			</div>
         <% end %>
	</div>
</div>
<% if logged_in? && current_seller.admin %>
	<%= link_to 'Delete Category', category_path(@category), method: :delete %>
<% end %>
<%= render 'posts/post', obj: @category_posts %>

app/views/layouts/_footer.html.erb
<small>Copyright © CEM</small> 

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="navbar-brand">
        <%= link_to 'CEM',root_path %>
      </div>
    </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="#">How it Works<span class="sr-only">(current)</span></a></li>
            <li><%= link_to 'Add Post', new_post_path %></li>
          <% end %>
        </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= if logged_in? && current_seller %>
                <li><%= link_to 'My Listings', seller_path(current_seller) %></li>
                <li><%= link_to 'Account Settings', edit_seller_path(current_seller) %></li>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <% else %>
                <li><%= link_to 'Log in', login_path %></li>
                <li><%= link_to 'Sign up', signup_path %></li>
          </ul>
      </div>
  </div>
</nav>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CemMvpTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/listings/_listing.html.erb
  <div class = "container-fluid">
    <div class = "row">
		<% obj.each do |listing| %>
		  <div class = "col-xs-6 col-md-3">
		    <div class = "thumbnail">
             <%= link_to image_tag(listing.image.url(:medium)), listing %>
			  <div class = "listing_name">
			   <p><%= listing.name %></p>
			 		<small>Seller: <%= link_to listing.seller.sellername,listing.seller if listing.seller %>
			   		  Updated <%= time_ago_in_words(listing.updated_at) %></small>
			   </div>
		     </div>
          </div>
		<% end %>
	</div>
  </div>	  
		

app/views/listings/edit.html.erb
<h1 style="text-align:center">Edit My Listing</h1>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for @listing do |l| %>

		    <%= l.label :name %>
		    <%= l.text_field :name, class: 'form-control' %>

			<%= l.label :description %>
			<%= l.text_area :description, class: 'form-control' %>

			<%= l.label :price %>
			<%= l.text_field :price, class: 'form-control' %>

			<%= l.label :condition %>
			<%= l.text_field :condition, class: 'form-control' %>

			<%= l.label :location %>
			<%= l.text_field :location, class: 'form-control' %>

			<%= l.label :image %>
			<%= l.file_field :image, class: 'form-control' %><br />

			<%= l.submit %>

			<% end %>
		</div>
	</div>

app/views/listings/index.html.erb
  <div class = "container-fluid">
    <div class = "row">
		<% @listing.each do |listing| %>
		  <div class = "col-xs-6 col-md-3">
		    <div class = "thumbnail">
		    <p><%= listing.name %></p>
            <%= link_to image_tag(listing.image.url(:medium)), listing %>
		    </div>
          </div>
		<% end %>
	</div>
  </div>	  
		

app/views/listings/new.html.erb
<%= render 'shared/errors', obj: @listing %>
<h1 style="text-align:center">Create a new Listing</h1>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for @listing do |l| %>
		    
		    <%= l.label :name %>
		    <%= l.text_field :name, class: "form-control" %>
			
			<%= l.label :description %>
			<%= l.text_area :description, class: "form-control" %>
			
			<%= l.label :price %>
			<%= l.text_field :price, class: "form-control" %>
			
			<%= l.label :condition %>
			<%= l.text_field :condition, class: "form-control" %>
			
			<%= l.label :location %>
			<%= l.text_field :location, class: "form-control" %>
			
			<%= l.label :image %>
			<%= l.file_field :image, class: "form-control"%><br /><br />

			<%= l.submit %>

		<% end %>
	</div>
</div>

app/views/listings/show.html.erb
<div class = "container-fluid">
	<div class = "jumbotron">
		<div class = "row">
			<div class = "listing_set_1">
				<div class = "col-md-12">
					<div class = "col-md-3">
						<%= @listing.name %>
					</div>
						<div class = "col-md-2"> 	
							<span class = "label label-info">
								<%= number_to_currency(@listing.price) %>
							</span>
						</div>
							<div class = "col-md-3">
								<%= @listing.condition %>
							</div>
				</div>
			</div>
				<div class = "col-md-12">
					<div class = "col-md-4">
						<%= image_tag @listing.image.url(:medium) %>
					</div>
						<div class = "col-md-4">
							<%= @listing.description %>
						</div>
				</div>
					<div class = "listing_set_3">
						<div class = "col-md-12">
					 		<div class = "col-md-4">
								<%= @listing.location %>
							</div>
								<% if (logged_in? && current_seller == @listing.seller) || (logged_in? && current_seller.admin?) %>
									<div class = "col-md-4">
										<%= link_to 'Add Listing', new_listing_path  %>
										<%= link_to 'Delete Listing', listing_path(@listing), method: :delete, data: { confirm: "Are you sure you want to delete this listing"} %>
										<%= link_to 'Edit Listing', edit_listing_path(@listing) %>
									</div>
								<% end %>
								<%= link_to 'More from this seller', @listing.seller if @listing.seller %>
						</div>
					</div>
		</div>
	</div>
</div>

app/views/posts/_post.html.erb
  <div class = "container-fluid">
    <div class = "row">
    	<% obj.each do |post| %>
		  <div class = "col-xs-6 col-md-3">
		    <div class = "thumbnail">
            <%= link_to image_tag(post.image.url(:medium)), post %>
             <div class = "post_index_title">
			  <p><%= post.title %></p>
		     </div>
		    </div>
          </div>
        <% end %>
	</div>
  </div>

app/views/posts/edit.html.erb
<h1 style="text-align:center">Edit Post</h1>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for @post do |f| %>
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control' %>
		
			  	<%= f.label :description %>
			  	<%= f.text_area :description, class: 'form-control' %>
			
			  	<%= f.label :image %>
			  	<%= f.file_field :image, class: 'form-control' %><br />
		
				<%= f.submit %>
			<% end %>
		</div>
	</div>

app/views/posts/index.html.erb
  <div class = "container-fluid">
    <div class = "row">
		<% @post.each do |post| %>
		  <div class = "col-xs-6 col-md-3">
		    <div class = "thumbnail">
            <%= link_to image_tag(post.image.url(:medium)), post %>
			<p><%= post.title %></p>
		    </div>
          </div>
		<% end %>
	</div>
  </div>	  
		

app/views/posts/new.html.erb
<%= render 'shared/errors', obj: @post %>
<h1 style="text-align:center">Create a new Post</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @post do |f| %>
	
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>

			<%= f.label :description %>
			<%= f.text_area :description, class: 'form-control' %>

			<%= f.label :image %>
			<%= f.file_field :image, class: 'form-control' %>
			<%= f.submit %>
	</div>
</div>
<% end %>

app/views/posts/show.html.erb
<%= link_to 'Back', categories_path, class: "btn btn-primary" %>
<div class = "container-fluid">
	<div class = "row">
		<div class = "col-xs-6 col-md-6">
			<%= image_tag @post.image.url(:large) %>
  				<div class = "post_show_title">
			  	  <p><%= @post.title %></p>
		        </div>
		          <div class = "post_show_description">
  			        <p><%= @post.description %></p>
  			      </div>
  			      	<% if logged_in? && current_seller.admin %>
  			      		<%= link_to 'Delete Post',post_path(@post), method: :delete %>
  			      	<% end %>
  		</div>
	</div>
</div>
<%= render 'listings/listing', obj: @post_listings %>

 

app/views/sellers/edit.html.erb
<h1 style="text-align:center">Edit My Seller Account</h1>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for @seller do |f| %>
				<%= f.label :sellername  %>
				<%= f.text_field :sellername, class: "form-control" %>
				
				<%= f.label :email %>
				<%= f.text_field :email, class: "form-control" %>
				
				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control" %>
				
				<%= f.label :location %>
				<%= f.text_field :location, class: "form-control" %>

				<%= f.label :site %>
				<%= f.text_field :site, class: "form-control" %><br />

				<%= f.submit 'Update my Account' %>

			<% end %>
				<%= link_to "Cancel", seller_path %><br />
		 </div>
	</div>

app/views/sellers/new.html.erb
<%= render 'shared/errors', obj: @seller %>
<h1 style="text-align:center">Create a new Seller Account</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
<%= form_for @seller do |f| %>

	<%= f.label :sellername  %>
	<%= f.text_field :sellername, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.text_field :email, class: 'form-control' %>

	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.label :location %>
	<%= f.text_field :location, class: 'form-control' %>

	<%= f.label :site %> 
	<%= f.text_field :site, class: 'form-control' %><br />

	<%= f.submit 'Lets Go', class: 'btn btn-primary' %>

<% end %>
</div>
</div>

app/views/sellers/show.html.erb
<h1>Welcome to <%= @seller.sellername %>'s Store </h1>
	<h2>This seller has <%= pluralize(@seller_listings.count, "product") if @seller_listings %> for sale</h2>
		<% if logged_in? && current_seller.admin? %>
			<%= link_to 'Delete this seller account', @seller, method: :delete, data: { confirm: "Are you sure?"} %>
		<% end %>
			<% if (logged_in? && current_seller == @seller) || (logged_in? && current_seller.admin) %>
				<%= link_to 'Add', new_listing_path %>
			<% end %> -->
				<%= render 'listings/listing', obj: @seller_listings %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<%= pluralize(obj.errors.count, "error") %>
		prevented this from from saving
		<% obj.errors.full_messages.each do |msg| %>
			<%= msg %>
		<% end %>
<% end %>